ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS questionnaire JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS gateways JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 5.0,
ADD COLUMN IF NOT EXISTS reviews INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS badge TEXT;
